import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import Provider from "../providers/provider";
import Footer from "../components/Footer";


export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} min-h-screen flex flex-col py-12 px-4 max-w-3xl mx-auto`}>
        <Provider>
          <main className="flex-1">
            {children}
          </main>
          <Footer />
        </Provider>
      </body>
    </html >
  );
}
