import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} min-h-screen flex flex-col py-12 px-4`}>
        <main className="flex-1">
          {children}
        </main>
        <footer className="text-center">Hell world footer</footer>
      </body>
    </html >
  );
}
